GCC toolchain: Add as to meson toolchain.txt
lowRISC/lowrisc-toolchains pull request #33
Opened 2020-09-01 08:27 UTC by imphil

2020-09-01 08:29 UTC, imphil commented
We need the assembler to build OTBN code, we currently rely on the GCC version of it. It's already built and packaged, but not listed in the `toolchain.txt`. Fix that.

2020-09-01 17:23 UTC, lenary requested changes
You also need to update `generate-clang-meson-cross-file.sh`. For the moment, point it at binutils `as`, like you have here.

2020-09-02 21:54 UTC, imphil commented
Ah ok, I didn't realize both toolchains are in the same directory next to each other. Updated.

2020-09-03 10:03 UTC, lenary approved these changes

2020-09-03 10:03 UTC, merged